tasks:
  - name: mysql
    init : |
      docker-compose up
  - name: dependencies
    init: |
      gp ports await 3306
      sudo cp settings.xml /home/gitpod/.m2
      mysql -u root -e "CREATE USER 'ors'@'localhost' IDENTIFIED BY 'ortaks21';"
      mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'ors'@'localhost' WITH GRANT OPTION;"
      mysql -u root -e "FLUSH PRIVILEGES;" 
      mysql -u root < init/orsdb.sql
      sudo mkdir /home/admin
      sudo unzip init/uploads.zip -d /home/gitpod
      wget -c https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz -P /workspace
      mkdir /workspace/tomcat
      tar -xf /workspace/apache-tomcat-9.0.76.tar.gz -C /workspace/tomcat --strip-components=1 
      rm -R /workspace/tomcat/webapps/ROOT
      cp deployments/ors.war /workspace/tomcat/webapps/ROOT.war
      export CATALINA_OPTS="$CATALINA_OPTS -Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true"
    command: sh /workspace/tomcat/bin/catalina.sh run
ports:
  - port: 3306
  - name: WebApp
    port: 8080
    onOpen: open-browser