services:
  db:
     image: mysql:5.7
     volumes:
       - /opt/test:/var/lib/mysql
       - ./init/orsdb.sql:/docker-entrypoint-initdb.d/datadump.sql 
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: orsdb
       MYSQL_USER: ors
       MYSQL_PASSWORD: ortaks21
     ports:
       - 3306:3306
     network_mode: "host"
